# Generated by Django 4.2.9 on 2024-01-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
